name = "psychiatric-frontend"
main = ".next/server/index.js"
compatibility_date = "2023-11-21"
account_id = "your_account_id"

# Variables de entorno
[vars]
NEXT_PUBLIC_API_URL = "https://mi-backend-api.liendoalejandro94.workers.dev/api"

# Build command
[build]
command = "npm run build"
watch_dir = "src"

# Static assets
[assets]
directory = ".next/static"

# Minify
minify = true

# Node.js compatibility
compatibility_flags = ["nodejs_compat"]